version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  techer-user:
    build: ./techer-user
    container_name: techer_user
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes: 
      - .:/usr/app
    links: 
      - db
    depends_on:
      - db
  techer-order:
    build: ./techer-orders
    container_name: techer-orders
    restart: always
    ports: 
      - 3000:3000
      - 5005:5005 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes: 
      - .:/usr/app
    links: 
      - db
    depends_on:
      - db
  frontend:
    build:
      context: ./techer-front
    ports:
      - "8080:8080"
    depends_on:
      - user_service
      - orders_service
      - db
volumes:
  db:
    driver: local