version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  app:
    build: ./techer-user
    container_name: techer_user
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes: 
      - .:/usr/app
    links: 
      - db
    depends_on:
      - db

volumes:
  db:
    driver: local